all:
	g++ ConsumerThread.cpp InterprocessQueue.cpp ProducerThread.cpp QueueTestConsole-Win32.cpp \
"/home/rosskw1/wc/Documents and Settings/rosskw1/My Documents/ComponentizedCombatSystemFramework/framework/utils/Exception.cpp" \
"/home/rosskw1/wc/Documents and Settings/rosskw1/My Documents/ComponentizedCombatSystemFramework/framework/utils/Thread.cpp" \
 -I/home/rosskw1/boost_build/include/boost-1_35 \
-I"/home/rosskw1/wc/Documents and Settings/rosskw1/My Documents/ComponentizedCombatSystemFramework/" \
-L/home/rosskw1/boost_build/lib -lboost_thread-gcc41-mt-1_35 -o QueueTest -g
